Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [24]:
import numpy as np

def vandermonde_matrix(inputVector, numberOfColumn, orderType):
    if orderType:
        return np.array([pow(iv,i) for iv in inputVector for i in range(numberOfColumn)]).reshape(len(inputVector), numberOfColumn)
    else:
        return np.array([pow(iv, numberOfColumn-i-1) for iv in inputVector for i in range(numberOfColumn)]).reshape(len(inputVector), numberOfColumn)
    
    
inputVector = np.array([1,2,3,4,5,6])
numberOfColumn = 3
print("Increasing matrix: \n")
print(vandermonde_matrix(inputVector, numberOfColumn ,True))
print("\nDecreasing matrix: \n")
print(vandermonde_matrix(inputVector, numberOfColumn ,False))


Increasing matrix: 

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]]

Decreasing matrix: 

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]]


----
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [50]:
input_vector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

window = 3

mvg = list()

for i in range(window, len(input_vector)+1):
    mvg.append(input_vector[i-window:i].mean())


print("Number of iteration the window take :" , len(mvg))
print("moving average : " , mvg)

Number of iteration the window take : 11
moving average :  [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
